#!/bin/sh
# ---------------------------------------------------------------------------
# archup.sh -- Check and install updates in Arch Linux
#
# Copyright 2017 Panagiotis Dimopoulos (panosdim@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at (http://www.gnu.org/licenses/) for
# more details.
#
# Version: 2.0
# ---------------------------------------------------------------------------

# Function that printout the correct usage of the script
usage()
{
cat << EOF

Usage: $0 [-c | -u | -h]

Without argument shows the available updates.

OPTIONS:
 -h      Show this message
 -c      Check for new available updates
 -u      Update the system

EOF
}

updsfile=/var/opt/archupdates
motdfile=/etc/motd

# Without any argument just printout the contents of updsfile
if [ $# -eq 0 ]; then
    if [ -s "$updsfile" ]; then
        cat "$updsfile"
        exit
    else
        echo "No packages need update."
    fi
fi

# Check input parameters and options
while getopts "hcu" optname; do
    case "$optname" in
    "h")
        usage
        exit
        ;;
    "c")
    	tmpfile=$(mktemp)
        chkupfile=$(mktemp)

        echo "Checking for new updates..."
        checkupdates > "$chkupfile"
        if [ -s "$chkupfile" ]; then
            # Check if chkupfile and updsfile are identical
            printf "\nFollowing packages need update\n" \
                | cat - "$chkupfile" > "$tmpfile" \
                && cp -f "$tmpfile" "$chkupfile"
            echo "" >> "$chkupfile"
            if cmp -s "$chkupfile" "$updsfile"; then
                cat "$updsfile"
                # Remove temporary files
                rm -rf "$tmpfile"
                rm -rf "$chkupfile"
                exit
            fi
			
			if [ "$EUID" -ne 0 ]; then
				rm -rf "$tmpfile"
				rm -rf "$chkupfile"
				exec sudo bash "$0" "$@"
			fi
			     	
            # Restore motd file
            grep -v -f "$updsfile" "$motdfile" > "$tmpfile"
            cp -f "$tmpfile" "$motdfile"

			# Add new packages that need update to motd
            cat "$chkupfile" > "$updsfile"
            cat "$updsfile" >> "$motdfile"

            # Remove temporary files
            rm -rf "$tmpfile"
            rm -rf "$chkupfile"

            cat "$updsfile"
            exit
        else
            echo "No packages need update."
        fi
        ;;
    "u")
 		if [ "$EUID" -ne 0 ]; then
 			exec sudo bash "$0" "$@"
 		fi 	   
    	tmpfile=$(mktemp)
        pacman --noconfirm -Syu
        grep -v -f "$updsfile" "$motdfile" > "$tmpfile"
        cp -f "$tmpfile" "$motdfile"
        true > "$updsfile"
        # Remove temporary files
        rm -rf "$tmpfile"
        ;;
    "?")
        usage
        exit
        ;;
    esac
done