#!/bin/sh
# ---------------------------------------------------------------------------
# archup.sh -- Check and install updates in Arch Linux
#
# Copyright 2017 Panagiotis Dimopoulos (panosdim@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at (http://www.gnu.org/licenses/) for
# more details.
#
# Version: 1.0
# ---------------------------------------------------------------------------

# Function that printout the correct usage of the script
usage()
{
cat << EOF

Usage: $0 [-c | -u | -h]

Without argument shows the available updates.

OPTIONS:
 -h      Show this message
 -c      Check for new available updates
 -u      Update the system

EOF
}

updsfile=/var/opt/archupdates
motdfile=/etc/motd
tmpfile=$(mktemp)
chkupfile=$(mktemp)

# Without any argument just printout the contents of updsfile
if [ $# -eq 0 ]; then
    if [ -s "$updsfile" ]; then
        cat "$updsfile"
        exit
    else
        echo "No packages need update."
    fi
fi

# Check input parameters and options
while getopts "hcu" optname; do
    case "$optname" in
    "h")
        usage
        exit
        ;;
    "c")
        echo "Checking for new updates..."
        checkupdates > "$chkupfile"
        if [ -s "$chkupfile" ]; then
            # Check if chkupfile and updsfile are identical
            echo "Following packages need update" \
                | cat - "$chkupfile" > "$tmpfile" \
                && cp -f "$tmpfile" "$chkupfile"
            if cmp -s "$chkupfile" "$updsfile"; then
                cat "$updsfile"
                exit
            fi

            # Restore motd file
            if [ "$(id -u)" != "0" ]; then
                sudo sh -c \
                    "grep -v -f \"$updsfile\" \"$motdfile\" > \"$tmpfile\"; \
                    cp -f \"$tmpfile\" \"$motdfile\""
            else
                grep -v -f "$updsfile" "$motdfile" > "$tmpfile"
                cp -f "$tmpfile" "$motdfile"
            fi

            # Add new packages that need update to motd
            cat "$chkupfile" > "$updsfile"
            if [ "$(id -u)" != "0" ]; then
                sudo sh -c "cat $updsfile >> $motdfile"
            else
                cat "$updsfile" >> "$motdfile"
            fi

            cat "$updsfile"
            exit
        else
            echo "No packages need update."
        fi
        ;;
    "u")
        if [ "$(id -u)" != "0" ]; then
            sudo sh -c "pacman -Syu; \
                grep -v -f \"$updsfile\" \"$motdfile\" > \"$tmpfile\"; \
                cp -f \"$tmpfile\" \"$motdfile\"; \
                true > \"$updsfile\""
        else
            pacman -Syu
            grep -v -f "$updsfile" "$motdfile" > "$tmpfile"
            cp -f "$tmpfile" "$motdfile"
            true > "$updsfile"
        fi
        ;;
    "?")
        usage
        exit
        ;;
    esac
done

rm -rf "$tmpfile"
rm -rf "$chkupfile"


