#!/bin/sh
# ---------------------------------------------------------------------------
# install.sh -- Install archup utility
#
# Copyright 2017 Panagiotis Dimopoulos (panosdim@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at (http://www.gnu.org/licenses/) for
# more details.
#
# Version: 1.0
# ---------------------------------------------------------------------------

if [ "$(id -u)" != "0" ]; then
    echo "You must be root or have root priviledges in order to install archup"
    exit 1
fi


# Check if checkupdates command is available
command -v checkupdates > /dev/null \
    || { echo "checkupdates command not found. Please install again pacman.";
        exit 1; }

cp archup /usr/bin
cp archup.service /usr/lib/systemd/system
cp archup.timer /usr/lib/systemd/system
systemctl start archup.timer
systemctl enable archup.timer
